### PR TITLE
run `generateIcons` at startup if sprite.svg does not exist

### LINKED ISSUE #2: Doesn't do anything? (reproduction included)
Hey Alem!👋 This looks cool, so I wanted to try it out but I can't seem to make it actually do anything (in dev nor when building for prod). It looks very simple, but I watched [the YT video](https://youtu.be/1yaMkLEY6LU?si=HPFTJp-hHQkgF0z1) just to make sure I wasn't doing something wrong. 😅 I must be having one of those days. What am I missing?!

Reproduction:

https://github.com/wKovacs64/remix-292-vite-spritesheet

(Note: I also cloned your repo and tried your example in `test-apps/remix-vite` but it doesn't work either.)

### PR DESCRIPTION
**Pull request by OnurGvnc**
Fixes #2

# Description

I noticed that the plugin wasn't running at startup for already existing files because it only watches for changes in the ﻿`inputDir` directory. To address this issue, I ensured that the ﻿`generateIcons` function runs at Vite startup if the sprite.svg file does not exist. This way, the sprite.svg file will be generated at the beginning if it is missing.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [x] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the UI is working as expected and is satisfactory
- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -141,6 +141,22 @@ export const iconsSpritesheet: (args: PluginProps) => Plugin = ({ withTypes, inp
   apply(config) {
     return config.mode === "development";
   },
+  async configResolved(config) {
+    const outputSvgPath = normalizePath(path.join(cwd ?? process.cwd(), outputDir, fileName ?? "sprite.svg"));
+    if (
+      !(await fs
+        .access(outputSvgPath, fs.constants.F_OK)
+        .then(() => true)
+        .catch(() => false))
```
Comment (AlemTuzlak) [inline src/index.ts:150]: could we extract this into a const right above this? I don't really like to have it in the if statement?

Comment (OnurGvnc) [reply src/index.ts:150]: Done, extracted into a const. Thanks

Comment (AlemTuzlak) [reply src/index.ts]: Awesome work. Thank you on this!

**Review by AlemTuzlak — APPROVED** [review]
